language: node_js
node_js:
  - "0.10"
before_install:
  - git submodule update --init --recursive
  - "curl -L http://git.io/ejPSng | /bin/sh"
env:
  - TEST_COMMAND=meteor
  - TEST_COMMAND=mrt METEOR_RELEASE=0.8.3